int id2i_openssl_no_hw_aep;
int id2i_sqlite_omit_decltype;
int id2i_sqlite_mutex_noop;
int id2i_config_feature_getopt_long;
int id2i_sixty_four_bit_long;
int id2i_config_xz;
int id2i_config_feature_runsvdir_log;
int id2i_ssl_forbid_enull;
int id2i_config_feature_prefer_ipv4_address;
int id2i_config_feature_initrd;
int id2i_sqlite_enable_cerod;
int id2i_config_feature_grep_egrep_alias;
int id2i_config_ls;
int id2i_config_feature_volumeid_ocfs2;
int id2i_config_ubidetach;
int id2i_config_feature_fbset_fancy;
int id2i_netscape_hang_bug;
int id2i_config_feature_expand_long_options;
int id2i_config_route;
int id2i_openssl_ssl_client_engine_auto;
int id2i_config_ftpget;
int id2i_debug_keygen;
int id2i_config_feature_tar_oldgnu_compatibility;
int id2i_config_feature_human_readable;
int id2i_config_feature_show_threads;
int id2i_config_feature_hdparm_get_identity;
int id2i_config_remove_shell;
int id2i_lock_debug;
int id2i_config_feature_hwclock_long_options;
int id2i_config_feature_etc_networks;
int id2i_crypto_mdebug_abort;
int id2i_config_pkill;
int id2i_sqlite_malloc_soft_limit;
int id2i_config_feature_modprobe_small_check_already_loaded;
int id2i_config_feature_bootchartd_bloated_header;
int id2i_config_feature_test_64;
int id2i_sqlite_omit_subquery;
int id2i_config_ioctl_hex2str_error;
int id2i_config_feature_tar_uname_gname;
int id2i_rsa_null;
int id2i_config_feature_setfont_textual_map;
int id2i_openssl_no_ripemd160;
int id2i_config_feature_clean_up;
int id2i_config_feature_hdparm_hdio_getset_dma;
int id2i_config_feature_ls_color;
int id2i_config_logger;
int id2i_config_feature_httpd_basic_auth;
int id2i_config_feature_mtab_support;
int id2i_config_feature_mount_nfs;
int id2i_openssl_no_tls1;
int id2i_config_header_bn_h;
int id2i_config_feature_tunctl_ug;
int id2i_config_feature_ipcalc_long_options;
int id2i_bn_mul_comba;
int id2i_rl_debug;
int id2i_config_feature_check_names;
int id2i_aes_wrap_test;
int id2i_config_uncompress;
int id2i_config_feature_cpio_o;
int id2i_config_feature_minix2;
int id2i___compile_capieng;
int id2i_config_feature_unexpand_long_options;
int id2i_config_feature_hdparm_hdio_drive_reset;
int id2i_config_feature_2_4_modules;
int id2i_des_default_options;
int id2i_header_bn_h;
int id2i_config_feature_traceroute_source_route;
int id2i_config_sha256sum;
int id2i_config_feature_chat_clr_abort;
int id2i_des_risc1;
int id2i_config_add_shell;
int id2i_config_feature_allow_exec;
int id2i_config_feature_brctl_fancy;
int id2i_md_rand_debug;
int id2i_config_feature_find_paren;
int id2i_config_feature_volumeid_sysv;
int id2i___tandem;
int id2i_config_feature_run_parts_fancy;
int id2i_config_feature_insmod_version_checking;
int id2i_no_asn1_old;
int id2i_cbc_handles_truncated_io;
int id2i_des_ptr;
int id2i_simics;
int id2i_config_feature_find_perm;
int id2i_openssl_no_hw_cswift;
int id2i_zlib_shared;
int id2i_config_feature_syslogd_dup;
int id2i_config_feature_hdparm_hdio_tristate_hwif;
int id2i___i386__;
int id2i_config_feature_ip_tunnel;
int id2i_pkcs12_broken_keygen;
int id2i_config_rpm;
int id2i_config_ash_builtin_printf;
int id2i_config_unxz;
int id2i_config_feature_tar_from;
int id2i_config_feature_editing_fancy_prompt;
int id2i_aephk_lib_name;
int id2i_config_feature_kill_removed;
int id2i_config_feature_volumeid_ntfs;
int id2i_old_str_to_key;
int id2i_config_feature_traceroute_verbose;
int id2i_sqlite_enable_oversize_cell_check;
int id2i_config_feature_fancy_tail;
int id2i_config_dpkg_deb;
int id2i_openssl_sun_gf2m_div;
int id2i_sqlite_enable_memsys3;
int id2i_floatifreslseln_sc;
int id2i_config_feature_insmod_load_map;
int id2i_config_feature_adduser_to_group;
int id2i_config_feature_pidof_omit;
int id2i_sqlite_enable_expensive_assert;
int id2i_config_feature_use_termios;
int id2i_config_base64;
int id2i___alpha;
int id2i__file_offset_bits;
int id2i_test_eng_openssl_no_algorithms;
int id2i_obj_xref_test2;
int id2i_config_feature_vi_set;
int id2i_no_windows_braindeath;
int id2i_openssl_no_dtls1;
int id2i_sqlite_enable_tree_explain;
int id2i_config_feature_netstat_prg;
int id2i_use_sha1_rand;
int id2i_config_tftpd;
int id2i_config_feature_df_fancy;
int id2i_sqlite_omit_builtin_test;
int id2i_engine_dynamic_support;
int id2i__m_ix86;
int id2i_config_feature_swapon_pri;
int id2i_config_unicode_wide_wchars;
int id2i_config_feature_ps_additional_columns;
int id2i_config_long_opts;
int id2i_config_feature_logread_reduced_locking;
int id2i_config_feature_utmp;
int id2i_getpid_is_meaningless;
int id2i_config_feature_vi_yankmark;
int id2i_config_uudecode;
int id2i_config_feature_tftp_get;
int id2i_config_feature_ftpd_accept_broken_list;
int id2i_config_feature_find_mtime;
int id2i_sqlite_enable_locking_style;
int id2i_config_feature_find_user;
int id2i_sqlite_omit_vacuum;
int id2i_config_feature_ar_long_filenames;
int id2i_config_lzop_compr_high;
int id2i_config_pidof;
int id2i_config_feature_traceroute_use_icmp;
int id2i_use_pread;
int id2i_config_feature_ifconfig_memstart_ioaddr_irq;
int id2i_i386;
int id2i_config_pmap;
int id2i_sqlite_no_sync;
int id2i_config_rpm2cpio;
int id2i_config_feature_ls_recursive;
int id2i_crypto_mdebug_time;
int id2i_config_feature_vi_colon;
int id2i_sqlite_enable_memory_management;
int id2i_config_feature_dmesg_pretty;
int id2i_config_feature_non_posix_cp;
int id2i_openssl_no_inline_asm;
int id2i_config_feature_fdisk_writable;
int id2i_config_feature_fancy_ping;
int id2i_config_echo;
int id2i_config_feature_buffers_go_in_bss;
int id2i_openssl_no_ssl2;
int id2i_openssl_no_hw_chil;
int id2i_config_feature_vi_readonly;
int id2i_config_feature_readlink_follow;
int id2i_openssl_no_descbcm;
int id2i_config_feature_chown_long_options;
int id2i_sol_tcp;
int id2i_config_feature_find_group;
int id2i_config_feature_find_not;
int id2i_scr_sysgen_sy;
int id2i_config_feature_vi_search;
int id2i_config_feature_date_isofmt;
int id2i_config_feature_udhcp_rfc3397;
int id2i_config_nandwrite;
int id2i_config_build_libbusybox;
int id2i_config_feature_ipv6;
int id2i_config_feature_mdev_rename_regexp;
int id2i_config_deluser;
int id2i_config_killall;
int id2i_test_eng_openssl_sha_p_update;
int id2i_config_feature_mount_loop_create;
int id2i_openssldir;
int id2i_bf_ptr2;
int id2i_config_feature_resize_print;
int id2i_sqlite_omit_cast;
int id2i_ssl_debug;
int id2i_debug_keys;
int id2i_config_feature_acpid_compat;
int id2i_config_adduser;
int id2i_sqlite_enable_fts4;
int id2i_config_feature_hexdump_reverse;
int id2i_openssl_implements_strncasecmp;
int id2i_config_feature_find_print0;
int id2i_config_feature_brctl_show;
int id2i_config_feature_prefer_applets;
int id2i_engine_conf_debug;
int id2i_config_feature_tar_oldsun_compatibility;
int id2i_config_selinux;
int id2i_config_feature_find_newer;
int id2i_config_feature_su_syslog;
int id2i_config_feature_volumeid_ext;
int id2i_no_gettod;
int id2i_openssl_sys_vos;
int id2i_openssl_no_dgram;
int id2i_sqlite_omit_blob_literal;
int id2i_config_feature_call_telinit;
int id2i_config_feature_ip_route;
int id2i_openssl_no_hw_nuron;
int id2i_config_feature_mount_cifs;
int id2i_config_feature_ifupdown_ipv4;
int id2i_config_bunzip2;
int id2i_config_feature_httpd_ranges;
int id2i_config_feature_telnet_ttype;
int id2i_config_feature_volumeid_luks;
int id2i_config_feature_insmod_loadinkmem;
int id2i_openssl_no_ssl3;
int id2i_config_feature_insmod_ksymoops_symbols;
int id2i__wrs_kernel;
int id2i_config_feature_inetd_rpc;
int id2i_config_unexpand;
int id2i_have_strerror_r;
int id2i_have_long_long;
int id2i_config_feature_volumeid_linuxswap;
int id2i_config_feature_httpd_cgi;
int id2i_config_feature_wget_authentication;
int id2i_config_feature_chat_nofail;
int id2i_openssl_no_rsax;
int id2i_config_sh_math_support_64;
int id2i_config_feature_check_tainted_module;
int id2i_config_stty;
int id2i_config_feature_httpd_set_remote_port_to_env;
int id2i_config_feature_netstat_wide;
int id2i__win32_wce;
int id2i_config_feature_crond_d;
int id2i_openssl_no_cast;
int id2i_doxygen;
int id2i_config_feature_httpd_config_with_script_interpr;
int id2i_config_locale_support;
int id2i_config_envuidgid;
int id2i_openssl_no_cms;
int id2i_config_feature_find_delete;
int id2i_config_feature_dd_ibs_obs;
int id2i_config_feature_tftp_put;
int id2i_config_feature_tar_create;
int id2i_config_devfsd_modload;
int id2i_config_feature_ifupdown_mapping;
int id2i_config_feature_find_regex;
int id2i_config_chpst;
int id2i_config_feature_tab_completion;
int id2i_config_feature_su_checks_shells;
int id2i_config_feature_modprobe_small_options_on_cmdline;
int id2i_w_ok;
int id2i_config_ping6;
int id2i_config_loadfont;
int id2i_config_devfsd_fg_np;
int id2i_termios;
int id2i_openssl_no_tls1_2_client;
int id2i_config_feature_volumeid_jfs;
int id2i_config_feature_md5_sha1_sum_check;
int id2i_config_feature_chcon_long_options;
int id2i_default_home;
int id2i_config_feature_verbose_cp_message;
int id2i_config_feature_rotate_logfile;
int id2i_config_dpkg;
int id2i_config_feature_inetd_support_builtin_daytime;
int id2i_ssl_ad_missing_srp_username;
int id2i_openssl_sys_sunos;
int id2i_openssl_no_hw_4758_cca;
int id2i_config_feature_ls_sortfiles;
int id2i_bit_field_limits;
int id2i_openssl_no_sha512;
int id2i_config_feature_securetty;
int id2i_config_expr_math_support_64;
int id2i__win64;
int id2i_header_crypto_h;
int id2i_config_feature_seamless_lzma;
int id2i_pkcs1_check;
int id2i___arch64__;
int id2i_openssl_no_idea;
int id2i_config_ftpput;
int id2i_config_feature_nameif_extended;
int id2i_app_init;
int id2i_config_feature_vi_setopts;
int id2i_config_feature_less_flags;
int id2i_config_feature_httpd_setuid;
int id2i_config_feature_mount_flags;
int id2i_openssl_no_ripemd;
int id2i_config_cpio;
int id2i_config_feature_inetd_support_builtin_discard;
int id2i_config_lzma;
int id2i__osd_posix;
int id2i_config_feature_less_winch;
int id2i_openssl_no_md4;
int id2i_sqlite_omit_pager_pragmas;
int id2i_no_sys_types_h;
int id2i_config_feature_ls_followlinks;
int id2i_openssl_no_srp;
int id2i_openssl_no_des;
int id2i_config_test;
int id2i_config_feature_hdparm_hdio_scan_hwif;
int id2i_config_freeramdisk;
int id2i_config_feature_devpts;
int id2i_config_feature_find_context;
int id2i_config_feature_httpd_encode_url_str;
int id2i_config_feature_hdparm_hdio_unregister_hwif;
int id2i_config_feature_vi_ask_terminal;
int id2i_config_feature_modprobe_blacklist;
int id2i_config_feature_shadowpasswds;
int id2i_config_feature_tar_to_command;
int id2i_debug_print_unknown_ciphersuites;
int id2i_config_feature_modutils_alias;
int id2i_config_feature_httpd_proxy;
int id2i_config_feature_nologin;
int id2i_config_feature_runcon_long_options;
int id2i_config_feature_seamless_z;
int id2i_config_feature_mount_fstab;
int id2i_bio_pair_debug;
int id2i_pedantic;
int id2i_dtls1_ad_missing_handshake_message;
int id2i_config_feature_volumeid_xfs;
int id2i_config_nc_110_compat;
int id2i_config_devfsd_verbose;
int id2i_debug_pkcs5v2;
int id2i_config_unicode_preserve_broken;
int id2i_config_feature_ftp_write;
int id2i_config_feature_find_exec;
int id2i_config_feature_insmod_try_mmap;
int id2i_config_feature_volumeid_linuxraid;
int id2i_predict;
int id2i_sqlite_ebcdic;
int id2i_config_feature_devfs;
int id2i_config_du;
int id2i_config_feature_ifupdown_external_dhcp;
int id2i_config_feature_vi_win_resize;
int id2i_aeprand;
int id2i_config_feature_wget_statusbar;
int id2i_sqlite_omit_pragma;
int id2i_des_unroll;
int id2i_config_feature_tee_use_block_io;
int id2i_config_feature_insmod_load_map_full;
int id2i_openssl_ri_debug;
int id2i_config_feature_grep_fgrep_alias;
int id2i_ref_check;
int id2i___ultrix;
int id2i_openssl_no_buf_freelists;
int id2i_openssl_no_rdrand;
int id2i_config_feature_ps_wide;
int id2i_sqlite_enable_update_delete_limit;
int id2i_config_setuidgid;
int id2i___need_file;
int id2i_config_feature_ipc_syslog;
int id2i_config_use_bb_crypt_sha;
int id2i_config_feature_seamless_xz;
int id2i_pkt_debug;
int id2i_aes_ctr_asm;
int id2i_sqlite_omit_deprecated;
int id2i_config_feature_aix_label;
int id2i_config_feature_editing_savehistory;
int id2i_config_feature_top_cpu_global_percents;
int id2i_vdbe_profile;
int id2i_openssl_no_gost;
int id2i_config_feature_date_compat;
int id2i_config_feature_volumeid_cramfs;
int id2i_openssl_no_hw_sureware;
int id2i_config_feature_username_completion;
int id2i_openssl_no_object;
int id2i_config_feature_vi_8bit;
int id2i_config_feature_ls_timestamps;
int id2i_no_md5crypt_1;
int id2i_config_passwd;
int id2i___mach__;
int id2i_openssl_use_ipv6;
int id2i_gost_lib_name;
int id2i_config_tftp_debug;
int id2i_ssl3_align_payload;
int id2i_openssl_no_setvbuf_ionbf;
int id2i_config_feature_less_brackets;
int id2i_config_feature_pidof_single;
int id2i_bn_sqr_comba;
int id2i_config_feature_makedevs_table;
int id2i_config_feature_bootchartd_config_file;
int id2i_config_feature_tr_classes;
int id2i_config_delgroup;
int id2i_config_feature_vi_dot_cmd;
int id2i___apple__;
int id2i_config_feature_stat_format;
int id2i_config_lfs;
int id2i_debug_sign;
int id2i_use_tod;
int id2i_config_syslogd;
int id2i_openssl_no_seed;
int id2i_config_feature_fdisk_advanced;
int id2i_config_feature_fancy_echo;
int id2i_config_ubiattach;
int id2i_config_feature_find_xdev;
int id2i_openssl_no_hw_ncipher;
int id2i_openssl_no_hw_atalla;
int id2i_rsa_debug;
int id2i_config_feature_ifconfig_hw;
int id2i_use_pread64;
int id2i_config_feature_find_size;
int id2i_config_feature_fancy_sleep;
int id2i_config_feature_volumeid_hfs;
int id2i_config_pgrep;
int id2i_crypto_mdebug;
int id2i_config_feature_tar_gnu_extensions;
int id2i_config_feature_dc_libm;
int id2i_config_traceroute6;
int id2i_config_feature_volumeid_fat;
int id2i_no_sys_un_h;
int id2i_engine_table_debug;
int id2i__xopen_source;
int id2i_config_feature_setconsole_long_options;
int id2i_config_feature_ip_address;
int id2i_config_swaponoff;
int id2i_openssl_no_x509_verify;
int id2i___apple_cc__;
int id2i_config_feature_udhcpc_arping;
int id2i_config_feature_env_long_options;
int id2i_config_feature_udhcp_port;
int id2i_config_feature_seamless_gz;
int id2i_config_feature_top_cpu_usage_percentage;
int id2i_sqlite_enable_column_metadata;
int id2i_config_feature_sort_big;
int id2i_sqlite_enable_fts3;
int id2i_config_feature_editing_vi;
int id2i_aes_xts_asm;
int id2i___i386;
int id2i_config_desktop;
int id2i_config_feature_gzip_long_options;
int id2i_config_feature_tar_selinux;
int id2i_sqlite_omit_autovacuum;
int id2i_config_verbose_resolution_errors;
int id2i_config_use_bb_shadow;
int id2i_config_debug;
int id2i_config_feature_xargs_support_zero_term;
int id2i_config_feature_lzma_fast;
int id2i_config_feature_dd_signal_handling;
int id2i_stitched_call;
int id2i_openssl_small_footprint;
int id2i_config_feature_reformime_compat;
int id2i_config_sha512sum;
int id2i_config_feature_telnet_autologin;
int id2i_config_feature_ip_rule;
int id2i_config_feature_mount_loop;
int id2i_openssl_no_camellia;
int id2i_config_feature_mount_fake;
int id2i_sqlite_small_stack;
int id2i_config_feature_setfiles_check_option;
int id2i_debug_decrypt;
int id2i___mwerks__;
int id2i_config_install_no_usr;
int id2i_string_table_test;
int id2i_sqlite_check_pages;
int id2i_sqlite_enable_sqllog;
int id2i_config_feature_find_mmin;
int id2i_tcp_nodelay;
int id2i_config_sha1sum;
int id2i_config_feature_taskset_fancy;
int id2i_config_tftp;
int id2i_config_ftpd;
int id2i_scr_massifc_sy;
int id2i_config_feature_udhcpd_write_leases_early;
int id2i_bn_recursion;
int id2i_config_feature_mount_label;
int id2i_modes_debug;
int id2i_config_feature_sun_label;
int id2i_config_feature_tar_autodetect;
int id2i_purify;
int id2i_config_envdir;
int id2i_config_feature_xargs_support_termopt;
int id2i_config_unlzma;
int id2i_config_feature_chat_tty_hifi;
int id2i_config_feature_grep_context;
int id2i_test_eng_openssl_sha_others;
int id2i_config_feature_cp_long_options;
int id2i_config_feature_httpd_gzip;
int id2i_config_feature_ls_filetypes;
int id2i_irix_cc_bug;
int id2i_config_feature_tr_equiv;
int id2i_gencb_test;
int id2i_config_feature_less_dashcmd;
int id2i_config_feature_top_decimals;
int id2i_config_feature_mdev_load_firmware;
int id2i_openssl_no_rc2;
int id2i_config_feature_extra_quiet;
int id2i_config_feature_check_unicode_in_env;
int id2i_data_order_is_big_endian;
int id2i_config_unicode_using_locale;
int id2i_test_eng_openssl_sha_p_init;
int id2i_openssl_no_rc4;
int id2i_config_feature_ls_color_is_default;
int id2i_config_feature_del_user_from_group;
int id2i_config_killall5;
int id2i_config_chown;
int id2i_sqlite_have_isnan;
int id2i_bn_count;
int id2i_config_feature_find_maxdepth;
int id2i_config_feature_dd_third_status_line;
int id2i_config_feature_compress_bbconfig;
int id2i_myalloc;
int id2i_config_feature_ar_create;
int id2i_do_test;
int id2i_config_feature_lsmod_pretty_2_6_output;
int id2i_config_flash_unlock;
int id2i_config_feature_ntpd_server;
int id2i_levitte_debug_mem;
int id2i_config_feature_chat_swallow_opts;
int id2i_config_feature_modutils_symbols;
int id2i_sqlite_omit_view;
int id2i_times;
int id2i_efence;
int id2i_config_feature_tar_long_options;
int id2i_config_feature_loadfont_psf2;
int id2i___decc;
int id2i_config_feature_loadfont_raw;
int id2i_config_feature_httpd_error_pages;
int id2i__sys_socket_h;
int id2i_config_nc_extra;
int id2i_config_feature_crond_call_sendmail;
int id2i_temp_gost_tls;
int id2i_config_feature_find_prune;
int id2i_cca4758_lib_name;
int id2i_ndebug;
int id2i_use_mdc2_rand;
int id2i_openssl_no_chain_verify;
int id2i_config_monotonic_syscall;
int id2i_config_feature_date_nano;
int id2i_openssl_sys_macosx;
int id2i_config_feature_ip_rare_protocols;
int id2i_openssl_no_sha0;
int id2i_no_old_asn1;
int id2i_x509_v3;
int id2i_config_feature_ftpgetput_long_options;
int id2i_config_softlimit;
int id2i__bsd_source;
int id2i_config_feature_cpio_p;
int id2i_config_feature_ifupdown_ipv6;
int id2i_config_feature_ip_link;
int id2i_config_feature_find_links;
int id2i_have_ubsec_dh;
int id2i_config_feature_osf_label;
int id2i_config_feature_fbset_readmode;
int id2i_config_feature_tftp_progress_bar;
int id2i_config_addgroup;
int id2i_config_feature_find_inum;
int id2i_config_feature_mdev_exec;
int id2i_openssl_no_ec2m;
int id2i_config_feature_less_linenums;
int id2i__aix;
int id2i_config_feature_find_path;
int id2i_test_eng_openssl_rc4_p_cipher;
int id2i_openssl_no_srtp;
int id2i_aes_debug;
int id2i_dynamic_engine;
int id2i_no_chmod;
int id2i_config_tar;
int id2i_sqlite_coverage_test;
int id2i_config_feature_hwclock_adjtime_fhs;
int id2i_config_feature_tar_nopreserve_time;
int id2i_fdatasync;
int id2i_openssl_policy_debug;
int id2i_openssl_no_nextprotoneg;
int id2i_config_scriptreplay;
int id2i_config_feature_rmdir_long_options;
int id2i_config_feature_use_inittab;
int id2i_config_feature_diff_long_options;
int id2i___rtp__;
int id2i_config_feature_xargs_support_quotes;
int id2i_config_feature_inetd_support_builtin_echo;
int id2i_config_feature_umount_all;
int id2i_have_fork;
int id2i_config_feature_vi_optimize_cursor;
int id2i_bf_default_options;
int id2i_sqlite_omit_or_optimization;
int id2i_config_feature_makedevs_leaf;
int id2i_config_hd;
int id2i_config_feature_topmem;
int id2i_config_feature_top_smp_process;
int id2i_config_pam;
int id2i_have_stdint_h;
int id2i_test_eng_openssl_rc4_others;
int id2i_openssl_no_static_engine;
int id2i_config_feature_telnetd_inetd_wait;
int id2i_config_fdflush;
int id2i_openssl_no_bf;
int id2i_config_feature_fast_top;
int id2i_config_feature_split_fancy;
int id2i_test_eng_openssl_sha_p_final;
int id2i_config_feature_mkdir_long_options;
int id2i_config_feature_du_default_blocksize_1k;
int id2i_config_use_bb_crypt;
int id2i_config_feature_init_coredumps;
int id2i_openssl_no_asm;
int id2i_bio_debug;
int id2i_capi_lib_name;
int id2i_config_feature_start_stop_daemon_long_options;
int id2i_config_feature_ifconfig_slip;
int id2i_sqlite_homegrown_recursive_mutex;
int id2i_config_feature_diff_dir;
int id2i_config_feature_volumeid_btrfs;
int id2i_config_feature_chat_var_abort_len;
int id2i_config_feature_ifconfig_status;
int id2i_config_feature_hwib;
int id2i_dnoxctl_var_sy;
int id2i_config_feature_wget_timeout;
int id2i_openssl_no_engine;
int id2i_openssl_no_hw_padlock;
int id2i_sqlite_omit_analyze;
int id2i_config_feature_mount_helpers;
int id2i_zlib;
int id2i_openssl_no_err;
int id2i_experimental_str_to_strong_key;
int id2i_config_feature_wc_large;
int id2i_config_feature_addgroup_long_options;
int id2i_config_feature_klogd_klogctl;
int id2i_config_feature_chat_send_escapes;
int id2i_config_expand;
int id2i_config_feature_volumeid_iso9660;
int id2i_config_feature_vi_use_signals;
int id2i_config_feature_xargs_support_confirmation;
int id2i_config_flash_lock;
int id2i_config_feature_inetd_support_builtin_time;
int id2i_config_feature_ifconfig_broadcast_plus;
int id2i_config_use_portable_code;
int id2i___beos__;
int id2i_crypto_mdebug_thread;
int id2i_config_feature_eject_scsi;
int id2i__cray;
int id2i_openssl_no_tls;
int id2i_config_feature_ipcalc_fancy;
int id2i_config_feature_volumeid_reiserfs;
int id2i_config_feature_top_smp_cpu;
int id2i_config_feature_ifupdown_ip;
int id2i_debug_zlib;
int id2i_config_fdisk_support_large_disks;
int id2i_sqlite_omit_load_extension;
int id2i_config_feature_remote_log;
int id2i_config_feature_volumeid_udf;
int id2i_config_feature_editing_ask_terminal;
int id2i_config_feature_awk_libm;
int id2i_config_feature_volumeid_romfs;
int id2i_config_nommu;
int id2i_sqlite_omit_explain;
int id2i_sqlite_default_memstatus;
int id2i_config_feature_httpd_use_sendfile;
int id2i_config_md5sum;
int id2i_config_feature_fancy_head;
int id2i___need___file;
int id2i_sqlite_enable_iotrace;
int id2i_b_endian;
int id2i_sqlite_enable_memsys5;
int id2i_test;
int id2i_config_feature_buffers_go_on_stack;
int id2i_config_sestatus;
int id2i_sqlite_enable_fts4_unicode61;
int id2i_config_feature_tftp_blocksize;
int id2i_config_include_susv2;
int id2i_header_e_os2_h;
int id2i_config_kill;
int id2i_config_feature_mdev_conf;
int id2i_pbe_prf_test;
int id2i_config_feature_find_depth;
int id2i_bn_ctx_debug;
int id2i_config_feature_seamless_bz2;
int id2i_config_feature_init_syslog;
int id2i_config_feature_mount_verbose;
int id2i_camellia_debug;
int id2i_config_feature_pidfile;
int id2i_config_feature_mkswap_uuid;
int id2i_openssl_no_hmac;
int id2i_config_feature_mdev_rename;
int id2i_config_feature_popmaildir_delivery;
int id2i_header_bn_lcl_h;
int id2i_config_nc_server;
int id2i_config_feature_init_sctty;
int id2i_config_feature_float_sleep;
int id2i_config_feature_telnetd_standalone;
int id2i_sqlite_omit_foreign_key;
int id2i_no_syslog;
int id2i_sixty_four_bit;
int id2i_sqlite_omit_attach;
int id2i_config_feature_ls_username;
int id2i_config_feature_less_regexp;
int id2i_config_feature_autowidth;
int id2i_config_feature_chat_implicit_cr;
int id2i_config_chpasswd;
int id2i_bn_debug;
int id2i_config_use_bb_pwd_grp;
int id2i_config_feature_start_stop_daemon_fancy;
int id2i_openssl_no_sock;
int id2i_config_setfont;
int id2i_config_printf;
int id2i_sqlite_rtree_int_only;
int id2i_config_feature_mv_long_options;
int id2i_config_feature_passwd_weak_check;
int id2i_crypto_mdebug_all;
int id2i_config_udhcpc;
int id2i_use_md5_rand;
int id2i_dnoxctl_dosctrlmod_sc;
int id2i_config_login_scripts;
int id2i_config_feature_inetd_support_builtin_chargen;
int id2i_config_feature_preserve_hardlinks;
int id2i_sqlite_has_codec;
int id2i_config_feature_run_parts_long_options;
int id2i_config_feature_httpd_auth_md5;
int id2i_have_long_double;
int id2i_conf_debug;
int id2i_config_feature_individual;
int id2i_pkcs_testvect;
int id2i_config_nanddump;
int id2i_config_feature_install_long_options;
int id2i_config_feature_find_type;
int id2i_config_feature_sgi_label;
int id2i_config_feature_syslog;
int id2i_config_feature_unix_local;
int id2i_config_hush;
int id2i_openssl_bn_asm_part_words;
int id2i_header_bss_file_c;
int id2i_openssl_no_psk;
int id2i_config_unicode_support;
int id2i_config_feature_adduser_long_options;
int id2i_selftest;
int id2i_config_gunzip;
int id2i_config_feature_less_marks;
int id2i_config_feature_shared_busybox;
void id2i_init()  {
  (id2i_sqlite_omit_load_extension = 0);
  (id2i_sqlite_rtree_int_only = 0);
  (id2i_config_feature_start_stop_daemon_fancy = 0);
  (id2i_config_feature_fancy_echo = 0);
  (id2i_config_swaponoff = 0);
  (id2i_cbc_handles_truncated_io = 0);
  (id2i_config_feature_find_prune = 0);
  (id2i_config_feature_syslogd_dup = 0);
  (id2i_config_feature_setconsole_long_options = 0);
  (id2i_debug_keygen = 0);
  (id2i_openssl_small_footprint = 0);
  (id2i_bn_mul_comba = 0);
  (id2i_config_feature_udhcp_rfc3397 = 0);
  (id2i_string_table_test = 0);
  (id2i_config_feature_mkdir_long_options = 0);
  (id2i_config_feature_volumeid_iso9660 = 0);
  (id2i_bio_pair_debug = 0);
  (id2i_config_feature_hdparm_get_identity = 0);
  (id2i_config_feature_run_parts_fancy = 0);
  (id2i_config_feature_ls_recursive = 0);
  (id2i_doxygen = 0);
  (id2i_rl_debug = 0);
  (id2i_config_ftpget = 0);
  (id2i_vdbe_profile = 0);
  (id2i_config_feature_dd_ibs_obs = 0);
  (id2i_config_killall5 = 0);
  (id2i_config_feature_httpd_proxy = 0);
  (id2i_sqlite_omit_subquery = 0);
  (id2i_config_feature_crond_d = 0);
  (id2i_config_feature_wget_authentication = 0);
  (id2i_config_feature_runsvdir_log = 0);
  (id2i_config_feature_tar_create = 0);
  (id2i_config_feature_xargs_support_zero_term = 0);
  (id2i_config_feature_ls_timestamps = 0);
  (id2i_config_flash_unlock = 0);
  (id2i_config_feature_find_links = 0);
  (id2i_config_feature_dd_third_status_line = 0);
  (id2i_config_feature_tee_use_block_io = 0);
  (id2i_aephk_lib_name = 0);
  (id2i_sqlite_no_sync = 0);
  (id2i_config_feature_popmaildir_delivery = 0);
  (id2i_test_eng_openssl_sha_p_final = 0);
  (id2i_config_feature_tftp_blocksize = 0);
  (id2i__bsd_source = 0);
  (id2i_config_feature_test_64 = 0);
  (id2i_config_feature_umount_all = 0);
  (id2i_config_feature_seamless_bz2 = 0);
  (id2i_config_feature_vi_setopts = 0);
  (id2i_config_feature_nameif_extended = 0);
  (id2i_config_feature_mkswap_uuid = 0);
  (id2i_sqlite_omit_vacuum = 0);
  (id2i_config_envdir = 0);
  (id2i_config_feature_check_unicode_in_env = 0);
  (id2i_config_feature_acpid_compat = 0);
  (id2i_sqlite_omit_explain = 0);
  (id2i_config_unicode_support = 0);
  (id2i_config_feature_awk_libm = 0);
  (id2i_sqlite_small_stack = 0);
  (id2i_config_cpio = 0);
  (id2i_config_feature_allow_exec = 0);
  (id2i_config_feature_use_termios = 0);
  (id2i_rsa_debug = 0);
  (id2i_use_tod = 0);
  (id2i_config_feature_cp_long_options = 0);
  (id2i_config_feature_modprobe_small_check_already_loaded = 0);
  (id2i_config_feature_find_paren = 0);
  (id2i_config_feature_reformime_compat = 0);
  (id2i___apple__ = 0);
  (id2i_config_softlimit = 0);
  (id2i_config_tftp = 0);
  (id2i_config_feature_volumeid_udf = 0);
  (id2i_config_feature_netstat_prg = 0);
  (id2i_config_bunzip2 = 0);
  (id2i_config_fdisk_support_large_disks = 0);
  (id2i_config_feature_tftp_progress_bar = 0);
  (id2i_config_ioctl_hex2str_error = 0);
  (id2i_openssl_no_rc2 = 0);
  (id2i_sol_tcp = 0);
  (id2i_config_devfsd_verbose = 0);
  (id2i_sixty_four_bit_long = 0);
  (id2i_config_use_bb_crypt_sha = 0);
  (id2i_config_devfsd_fg_np = 0);
  (id2i_header_e_os2_h = 0);
  (id2i_config_feature_telnet_ttype = 0);
  (id2i_sqlite_enable_column_metadata = 0);
  (id2i_config_feature_mdev_conf = 0);
  (id2i_config_feature_top_decimals = 0);
  (id2i_sqlite_enable_sqllog = 0);
  (id2i_openssl_ssl_client_engine_auto = 0);
  (id2i_config_chpst = 0);
  (id2i_dnoxctl_var_sy = 0);
  (id2i_config_feature_hwclock_adjtime_fhs = 0);
  (id2i_use_sha1_rand = 0);
  (id2i_config_feature_chown_long_options = 0);
  (id2i_use_pread = 0);
  (id2i_pkt_debug = 0);
  (id2i_config_feature_df_fancy = 0);
  (id2i_levitte_debug_mem = 0);
  (id2i_config_unlzma = 0);
  (id2i_config_ash_builtin_printf = 0);
  (id2i_openssl_no_cms = 0);
  (id2i_config_feature_tar_nopreserve_time = 0);
  (id2i_config_feature_grep_context = 0);
  (id2i_crypto_mdebug = 0);
  (id2i_config_expand = 0);
  (id2i_config_feature_loadfont_raw = 0);
  (id2i_config_feature_kill_removed = 0);
  (id2i_no_syslog = 0);
  (id2i_config_feature_find_inum = 0);
  (id2i_config_feature_traceroute_use_icmp = 0);
  (id2i_config_feature_makedevs_table = 0);
  (id2i_config_pidof = 0);
  (id2i_config_feature_ar_long_filenames = 0);
  (id2i_config_feature_ifconfig_slip = 0);
  (id2i_config_debug = 0);
  (id2i_scr_massifc_sy = 0);
  (id2i_config_feature_httpd_ranges = 0);
  (id2i_config_loadfont = 0);
  (id2i_config_uudecode = 0);
  (id2i_pkcs_testvect = 0);
  (id2i_config_feature_xargs_support_termopt = 0);
  (id2i_crypto_mdebug_thread = 0);
  (id2i_config_feature_dc_libm = 0);
  (id2i_config_scriptreplay = 0);
  (id2i_header_crypto_h = 0);
  (id2i_tcp_nodelay = 0);
  (id2i_config_feature_lsmod_pretty_2_6_output = 0);
  (id2i_old_str_to_key = 0);
  (id2i_config_feature_mount_fake = 0);
  (id2i_openssl_no_dtls1 = 0);
  (id2i_header_bn_lcl_h = 0);
  (id2i_config_feature_unix_local = 0);
  (id2i_config_feature_vi_win_resize = 0);
  (id2i_openssl_ri_debug = 0);
  (id2i_config_feature_sort_big = 0);
  (id2i_gencb_test = 0);
  (id2i_config_feature_top_smp_process = 0);
  (id2i_config_feature_inetd_support_builtin_daytime = 0);
  (id2i_obj_xref_test2 = 0);
  (id2i_dynamic_engine = 0);
  (id2i_config_feature_individual = 0);
  (id2i__sys_socket_h = 0);
  (id2i_pbe_prf_test = 0);
  (id2i_bit_field_limits = 0);
  (id2i_config_feature_ipc_syslog = 0);
  (id2i_config_feature_volumeid_ext = 0);
  (id2i_sqlite_enable_memsys3 = 0);
  (id2i_openssl_no_rsax = 0);
  (id2i_no_old_asn1 = 0);
  (id2i_config_sestatus = 0);
  (id2i_config_feature_tab_completion = 0);
  (id2i_config_feature_httpd_use_sendfile = 0);
  (id2i_config_feature_top_cpu_global_percents = 0);
  (id2i_config_feature_volumeid_hfs = 0);
  (id2i__aix = 0);
  (id2i_config_feature_top_smp_cpu = 0);
  (id2i_config_feature_brctl_show = 0);
  (id2i_ssl_ad_missing_srp_username = 0);
  (id2i_config_unexpand = 0);
  (id2i_config_feature_adduser_long_options = 0);
  (id2i_termios = 0);
  (id2i_config_setuidgid = 0);
  (id2i_openssl_no_ripemd160 = 0);
  (id2i_config_feature_buffers_go_on_stack = 0);
  (id2i_config_feature_hwib = 0);
  (id2i_config_feature_ps_wide = 0);
  (id2i___beos__ = 0);
  (id2i_header_bn_h = 0);
  (id2i_config_feature_editing_ask_terminal = 0);
  (id2i_config_feature_grep_egrep_alias = 0);
  (id2i_config_feature_ifupdown_mapping = 0);
  (id2i_irix_cc_bug = 0);
  (id2i_cca4758_lib_name = 0);
  (id2i_openssl_policy_debug = 0);
  (id2i_config_feature_vi_use_signals = 0);
  (id2i_config_feature_hdparm_hdio_unregister_hwif = 0);
  (id2i_config_feature_mdev_load_firmware = 0);
  (id2i_config_feature_eject_scsi = 0);
  (id2i_config_feature_crond_call_sendmail = 0);
  (id2i_sqlite_enable_expensive_assert = 0);
  (id2i_config_envuidgid = 0);
  (id2i_header_bss_file_c = 0);
  (id2i_config_ftpd = 0);
  (id2i_config_md5sum = 0);
  (id2i_config_feature_chat_implicit_cr = 0);
  (id2i_config_feature_vi_readonly = 0);
  (id2i_engine_dynamic_support = 0);
  (id2i_config_feature_volumeid_cramfs = 0);
  (id2i_config_login_scripts = 0);
  (id2i_config_setfont = 0);
  (id2i_config_feature_mdev_rename = 0);
  (id2i_have_long_long = 0);
  (id2i_config_feature_ip_route = 0);
  (id2i_config_feature_find_mtime = 0);
  (id2i_config_feature_find_exec = 0);
  (id2i_config_feature_chat_clr_abort = 0);
  (id2i_config_feature_use_inittab = 0);
  (id2i_sixty_four_bit = 0);
  (id2i_config_feature_pidof_single = 0);
  (id2i_config_feature_start_stop_daemon_long_options = 0);
  (id2i_config_feature_volumeid_sysv = 0);
  (id2i_no_asn1_old = 0);
  (id2i_md_rand_debug = 0);
  (id2i_config_feature_lzma_fast = 0);
  (id2i_config_feature_mount_loop = 0);
  (id2i_lock_debug = 0);
  (id2i_config_verbose_resolution_errors = 0);
  (id2i___arch64__ = 0);
  (id2i_fdatasync = 0);
  (id2i_config_feature_ifconfig_status = 0);
  (id2i_config_feature_hdparm_hdio_getset_dma = 0);
  (id2i_config_feature_mdev_rename_regexp = 0);
  (id2i_config_feature_ifupdown_ipv6 = 0);
  (id2i_debug_decrypt = 0);
  (id2i_config_add_shell = 0);
  (id2i_config_feature_fdisk_advanced = 0);
  (id2i_openssl_no_object = 0);
  (id2i_config_feature_vi_dot_cmd = 0);
  (id2i_config_feature_ipcalc_fancy = 0);
  (id2i_myalloc = 0);
  (id2i_config_feature_ifconfig_broadcast_plus = 0);
  (id2i_config_feature_less_dashcmd = 0);
  (id2i__cray = 0);
  (id2i_sqlite_enable_iotrace = 0);
  (id2i_config_feature_getopt_long = 0);
  (id2i_config_feature_ls_username = 0);
  (id2i_config_feature_ls_sortfiles = 0);
  (id2i_config_feature_find_user = 0);
  (id2i_openssl_no_tls = 0);
  (id2i_config_feature_2_4_modules = 0);
  (id2i_have_fork = 0);
  (id2i_openssl_no_tls1_2_client = 0);
  (id2i_use_mdc2_rand = 0);
  (id2i_pedantic = 0);
  (id2i_config_feature_httpd_error_pages = 0);
  (id2i_config_feature_find_perm = 0);
  (id2i_config_pgrep = 0);
  (id2i_bn_recursion = 0);
  (id2i_config_feature_find_delete = 0);
  (id2i_camellia_debug = 0);
  (id2i_openssl_no_hw_padlock = 0);
  (id2i___apple_cc__ = 0);
  (id2i_sqlite_mutex_noop = 0);
  (id2i_config_feature_bootchartd_bloated_header = 0);
  (id2i_config_monotonic_syscall = 0);
  (id2i_config_nanddump = 0);
  (id2i_config_feature_modprobe_small_options_on_cmdline = 0);
  (id2i_config_feature_volumeid_fat = 0);
  (id2i_config_feature_find_print0 = 0);
  (id2i_config_feature_check_tainted_module = 0);
  (id2i_w_ok = 0);
  (id2i_have_strerror_r = 0);
  (id2i_config_feature_volumeid_jfs = 0);
  (id2i___compile_capieng = 0);
  (id2i_config_feature_find_type = 0);
  (id2i_config_feature_osf_label = 0);
  (id2i_config_feature_tar_gnu_extensions = 0);
  (id2i_config_addgroup = 0);
  (id2i_sqlite_omit_pragma = 0);
  (id2i_config_feature_top_cpu_usage_percentage = 0);
  (id2i_config_feature_mtab_support = 0);
  (id2i_config_feature_hdparm_hdio_tristate_hwif = 0);
  (id2i_config_deluser = 0);
  (id2i_config_feature_ps_additional_columns = 0);
  (id2i_config_nandwrite = 0);
  (id2i_no_sys_un_h = 0);
  (id2i_config_feature_tunctl_ug = 0);
  (id2i_temp_gost_tls = 0);
  (id2i_config_feature_tr_classes = 0);
  (id2i_config_feature_klogd_klogctl = 0);
  (id2i_sqlite_enable_fts4_unicode61 = 0);
  (id2i__win64 = 0);
  (id2i_sqlite_enable_memsys5 = 0);
  (id2i_bn_count = 0);
  (id2i_config_feature_shared_busybox = 0);
  (id2i_openssl_no_hw_cswift = 0);
  (id2i_rsa_null = 0);
  (id2i_config_feature_diff_long_options = 0);
  (id2i_config_feature_inetd_support_builtin_echo = 0);
  (id2i_config_feature_tar_uname_gname = 0);
  (id2i_config_feature_env_long_options = 0);
  (id2i_config_feature_taskset_fancy = 0);
  (id2i_engine_table_debug = 0);
  (id2i_config_feature_tar_oldgnu_compatibility = 0);
  (id2i_openssl_use_ipv6 = 0);
  (id2i_openssl_no_srp = 0);
  (id2i_openssl_no_srtp = 0);
  (id2i_config_feature_less_linenums = 0);
  (id2i_aes_ctr_asm = 0);
  (id2i_config_feature_del_user_from_group = 0);
  (id2i_config_feature_ifupdown_ip = 0);
  (id2i_dnoxctl_dosctrlmod_sc = 0);
  (id2i_sqlite_malloc_soft_limit = 0);
  (id2i_config_base64 = 0);
  (id2i_bio_debug = 0);
  (id2i_openssl_no_hw_atalla = 0);
  (id2i_config_feature_diff_dir = 0);
  (id2i_config_feature_ftpd_accept_broken_list = 0);
  (id2i_config_feature_xargs_support_quotes = 0);
  (id2i_config_unicode_using_locale = 0);
  (id2i_config_feature_telnetd_standalone = 0);
  (id2i_config_feature_chat_nofail = 0);
  (id2i_sqlite_has_codec = 0);
  (id2i_config_feature_find_path = 0);
  (id2i_x509_v3 = 0);
  (id2i_config_feature_makedevs_leaf = 0);
  (id2i_config_hush = 0);
  (id2i_config_feature_find_group = 0);
  (id2i_use_pread64 = 0);
  (id2i_sqlite_enable_tree_explain = 0);
  (id2i_config_feature_md5_sha1_sum_check = 0);
  (id2i_config_feature_chcon_long_options = 0);
  (id2i_config_feature_tftp_get = 0);
  (id2i_config_lzma = 0);
  (id2i_config_feature_pidof_omit = 0);
  (id2i_config_feature_username_completion = 0);
  (id2i_predict = 0);
  (id2i_config_devfsd_modload = 0);
  (id2i_no_chmod = 0);
  (id2i_config_feature_tar_selinux = 0);
  (id2i_config_rpm = 0);
  (id2i_config_feature_vi_search = 0);
  (id2i_config_feature_editing_vi = 0);
  (id2i_config_feature_less_marks = 0);
  (id2i_openssl_no_hw_4758_cca = 0);
  (id2i_config_feature_insmod_ksymoops_symbols = 0);
  (id2i_crypto_mdebug_time = 0);
  (id2i_scr_sysgen_sy = 0);
  (id2i_config_feature_ip_rule = 0);
  (id2i_config_dpkg = 0);
  (id2i_openssl_no_dgram = 0);
  (id2i_openssl_no_static_engine = 0);
  (id2i_config_printf = 0);
  (id2i_floatifreslseln_sc = 0);
  (id2i_config_feature_fancy_tail = 0);
  (id2i_test_eng_openssl_sha_p_init = 0);
  (id2i_config_stty = 0);
  (id2i___rtp__ = 0);
  (id2i_config_feature_su_syslog = 0);
  (id2i_config_feature_buffers_go_in_bss = 0);
  (id2i_config_feature_init_sctty = 0);
  (id2i_config_feature_tr_equiv = 0);
  (id2i_openssldir = 0);
  (id2i_config_tftp_debug = 0);
  (id2i_openssl_no_des = 0);
  (id2i_config_pam = 0);
  (id2i_config_feature_split_fancy = 0);
  (id2i_config_feature_udhcpc_arping = 0);
  (id2i_config_feature_ip_rare_protocols = 0);
  (id2i_openssl_no_err = 0);
  (id2i_config_pmap = 0);
  (id2i_config_feature_aix_label = 0);
  (id2i_config_feature_fast_top = 0);
  (id2i_config_feature_less_regexp = 0);
  (id2i_getpid_is_meaningless = 0);
  (id2i_sqlite_have_isnan = 0);
  (id2i_config_lfs = 0);
  (id2i_config_build_libbusybox = 0);
  (id2i_openssl_no_camellia = 0);
  (id2i_sqlite_enable_update_delete_limit = 0);
  (id2i_config_feature_vi_set = 0);
  (id2i_config_feature_insmod_loadinkmem = 0);
  (id2i_config_logger = 0);
  (id2i_config_test = 0);
  (id2i_config_feature_nologin = 0);
  (id2i_openssl_no_seed = 0);
  (id2i_config_udhcpc = 0);
  (id2i_openssl_sys_macosx = 0);
  (id2i_test_eng_openssl_rc4_p_cipher = 0);
  (id2i_config_feature_traceroute_source_route = 0);
  (id2i_config_syslogd = 0);
  (id2i_openssl_no_ec2m = 0);
  (id2i_config_feature_resize_print = 0);
  (id2i_config_feature_hdparm_hdio_scan_hwif = 0);
  (id2i_config_feature_httpd_set_remote_port_to_env = 0);
  (id2i_openssl_no_psk = 0);
  (id2i_config_feature_find_newer = 0);
  (id2i_aes_xts_asm = 0);
  (id2i_config_feature_httpd_gzip = 0);
  (id2i_openssl_no_bf = 0);
  (id2i_config_feature_dmesg_pretty = 0);
  (id2i___tandem = 0);
  (id2i_config_feature_chat_swallow_opts = 0);
  (id2i_config_feature_mount_loop_create = 0);
  (id2i__osd_posix = 0);
  (id2i_config_feature_extra_quiet = 0);
  (id2i_config_expr_math_support_64 = 0);
  (id2i_openssl_no_hw_aep = 0);
  (id2i_config_sha512sum = 0);
  (id2i_config_feature_securetty = 0);
  (id2i_config_feature_mount_label = 0);
  (id2i_config_feature_inetd_rpc = 0);
  (id2i_config_kill = 0);
  (id2i_config_feature_rotate_logfile = 0);
  (id2i_config_feature_chat_var_abort_len = 0);
  (id2i___need___file = 0);
  (id2i_sqlite_omit_decltype = 0);
  (id2i_config_feature_date_isofmt = 0);
  (id2i_config_du = 0);
  (id2i_netscape_hang_bug = 0);
  (id2i_config_feature_hexdump_reverse = 0);
  (id2i_config_use_bb_pwd_grp = 0);
  (id2i_test_eng_openssl_rc4_others = 0);
  (id2i_config_feature_clean_up = 0);
  (id2i_config_feature_ls_followlinks = 0);
  (id2i__wrs_kernel = 0);
  (id2i_config_passwd = 0);
  (id2i_config_feature_logread_reduced_locking = 0);
  (id2i__xopen_source = 0);
  (id2i_config_traceroute6 = 0);
  (id2i_config_feature_fancy_ping = 0);
  (id2i_config_feature_ifconfig_hw = 0);
  (id2i_config_route = 0);
  (id2i_debug_keys = 0);
  (id2i_openssl_no_nextprotoneg = 0);
  (id2i_config_feature_sgi_label = 0);
  (id2i_config_feature_syslog = 0);
  (id2i_config_feature_ls_color = 0);
  (id2i_sqlite_ebcdic = 0);
  (id2i_config_feature_tar_autodetect = 0);
  (id2i_openssl_no_ssl2 = 0);
  (id2i_config_feature_chat_send_escapes = 0);
  (id2i_bn_debug = 0);
  (id2i_conf_debug = 0);
  (id2i_config_feature_fancy_sleep = 0);
  (id2i_config_feature_mount_cifs = 0);
  (id2i___mach__ = 0);
  (id2i_sqlite_homegrown_recursive_mutex = 0);
  (id2i_have_ubsec_dh = 0);
  (id2i_config_feature_telnetd_inetd_wait = 0);
  (id2i_have_long_double = 0);
  (id2i_config_feature_mount_flags = 0);
  (id2i_config_feature_minix2 = 0);
  (id2i_config_feature_initrd = 0);
  (id2i_config_feature_tar_long_options = 0);
  (id2i_config_feature_du_default_blocksize_1k = 0);
  (id2i_config_feature_topmem = 0);
  (id2i_capi_lib_name = 0);
  (id2i_efence = 0);
  (id2i_config_ftpput = 0);
  (id2i_config_lzop_compr_high = 0);
  (id2i_openssl_no_rdrand = 0);
  (id2i_config_feature_dd_signal_handling = 0);
  (id2i___i386__ = 0);
  (id2i_config_feature_tftp_put = 0);
  (id2i_config_feature_httpd_auth_md5 = 0);
  (id2i_config_unicode_preserve_broken = 0);
  (id2i_config_feature_prefer_ipv4_address = 0);
  (id2i_openssl_no_hw_chil = 0);
  (id2i_selftest = 0);
  (id2i_config_feature_bootchartd_config_file = 0);
  (id2i_config_feature_inetd_support_builtin_discard = 0);
  (id2i_config_feature_vi_yankmark = 0);
  (id2i_config_ls = 0);
  (id2i_config_feature_less_brackets = 0);
  (id2i_test_eng_openssl_sha_p_update = 0);
  (id2i_config_feature_find_not = 0);
  (id2i_config_fdflush = 0);
  (id2i_config_nc_server = 0);
  (id2i_openssl_no_hw_ncipher = 0);
  (id2i_config_feature_find_xdev = 0);
  (id2i_config_feature_check_names = 0);
  (id2i_config_pkill = 0);
  (id2i_config_feature_seamless_gz = 0);
  (id2i_config_dpkg_deb = 0);
  (id2i_config_nommu = 0);
  (id2i_config_install_no_usr = 0);
  (id2i_config_feature_loadfont_psf2 = 0);
  (id2i_openssl_no_cast = 0);
  (id2i_config_feature_vi_ask_terminal = 0);
  (id2i_openssl_no_hmac = 0);
  (id2i___need_file = 0);
  (id2i_config_feature_stat_format = 0);
  (id2i_config_feature_readlink_follow = 0);
  (id2i_sqlite_enable_fts3 = 0);
  (id2i_config_unicode_wide_wchars = 0);
  (id2i___mwerks__ = 0);
  (id2i_config_feature_editing_fancy_prompt = 0);
  (id2i_no_sys_types_h = 0);
  (id2i_config_feature_volumeid_linuxswap = 0);
  (id2i_config_feature_fancy_head = 0);
  (id2i_ssl_debug = 0);
  (id2i_ssl3_align_payload = 0);
  (id2i_config_feature_telnet_autologin = 0);
  (id2i_config_feature_find_mmin = 0);
  (id2i_times = 0);
  (id2i_aeprand = 0);
  (id2i_openssl_no_tls1 = 0);
  (id2i_config_tftpd = 0);
  (id2i_openssl_no_asm = 0);
  (id2i_config_feature_mount_verbose = 0);
  (id2i_openssl_no_sock = 0);
  (id2i_config_locale_support = 0);
  (id2i_config_feature_pidfile = 0);
  (id2i_use_md5_rand = 0);
  (id2i_config_long_opts = 0);
  (id2i_openssl_no_sha512 = 0);
  (id2i_stitched_call = 0);
  (id2i_bf_ptr2 = 0);
  (id2i_config_include_susv2 = 0);
  (id2i_config_sha1sum = 0);
  (id2i_config_chpasswd = 0);
  (id2i_config_feature_inetd_support_builtin_chargen = 0);
  (id2i_openssl_no_hw_nuron = 0);
  (id2i_sqlite_omit_view = 0);
  (id2i___i386 = 0);
  (id2i_openssl_no_sha0 = 0);
  (id2i_config_feature_mount_fstab = 0);
  (id2i_config_feature_setfont_textual_map = 0);
  (id2i_config_feature_passwd_weak_check = 0);
  (id2i_config_feature_editing_savehistory = 0);
  (id2i_no_gettod = 0);
  (id2i_config_use_bb_crypt = 0);
  (id2i_config_feature_modutils_alias = 0);
  (id2i_config_feature_modprobe_blacklist = 0);
  (id2i_sqlite_omit_attach = 0);
  (id2i_config_feature_volumeid_btrfs = 0);
  (id2i_config_use_portable_code = 0);
  (id2i_config_killall = 0);
  (id2i_config_feature_ntpd_server = 0);
  (id2i_test_eng_openssl_no_algorithms = 0);
  (id2i_openssl_no_gost = 0);
  (id2i_config_feature_mdev_exec = 0);
  (id2i_openssl_no_chain_verify = 0);
  (id2i_sqlite_enable_cerod = 0);
  (id2i_config_feature_tar_to_command = 0);
  (id2i_config_feature_volumeid_romfs = 0);
  (id2i_config_feature_volumeid_ocfs2 = 0);
  (id2i_config_feature_insmod_try_mmap = 0);
  (id2i_no_md5crypt_1 = 0);
  (id2i_sqlite_check_pages = 0);
  (id2i_experimental_str_to_strong_key = 0);
  (id2i_config_delgroup = 0);
  (id2i_config_feature_find_depth = 0);
  (id2i_config_feature_ip_tunnel = 0);
  (id2i_config_feature_swapon_pri = 0);
  (id2i_ssl_forbid_enull = 0);
  (id2i_config_feature_less_winch = 0);
  (id2i_config_feature_human_readable = 0);
  (id2i_config_feature_udhcp_port = 0);
  (id2i_config_feature_volumeid_luks = 0);
  (id2i_openssl_no_inline_asm = 0);
  (id2i_config_hd = 0);
  (id2i_config_feature_httpd_basic_auth = 0);
  (id2i_config_feature_ifupdown_external_dhcp = 0);
  (id2i_config_feature_traceroute_verbose = 0);
  (id2i_openssl_sys_sunos = 0);
  (id2i_des_risc1 = 0);
  (id2i_sqlite_omit_builtin_test = 0);
  (id2i_config_feature_utmp = 0);
  (id2i_config_echo = 0);
  (id2i_openssl_bn_asm_part_words = 0);
  (id2i_ref_check = 0);
  (id2i_config_feature_sun_label = 0);
  (id2i_config_adduser = 0);
  (id2i_config_feature_devfs = 0);
  (id2i_config_feature_inetd_support_builtin_time = 0);
  (id2i_config_feature_install_long_options = 0);
  (id2i_config_feature_httpd_encode_url_str = 0);
  (id2i_sqlite_omit_cast = 0);
  (id2i_config_feature_autowidth = 0);
  (id2i_config_feature_httpd_config_with_script_interpr = 0);
  (id2i___ultrix = 0);
  (id2i_des_default_options = 0);
  (id2i_config_ubidetach = 0);
  (id2i_des_ptr = 0);
  (id2i_do_test = 0);
  (id2i_ndebug = 0);
  (id2i_config_header_bn_h = 0);
  (id2i_config_feature_ftpgetput_long_options = 0);
  (id2i_config_feature_ip_address = 0);
  (id2i_config_feature_preserve_hardlinks = 0);
  (id2i_config_feature_insmod_load_map_full = 0);
  (id2i_openssl_sys_vos = 0);
  (id2i_config_feature_find_size = 0);
  (id2i_config_feature_ar_create = 0);
  (id2i_openssl_no_x509_verify = 0);
  (id2i_config_feature_date_compat = 0);
  (id2i_config_remove_shell = 0);
  (id2i_pkcs1_check = 0);
  (id2i_config_freeramdisk = 0);
  (id2i_config_feature_etc_networks = 0);
  (id2i_config_gunzip = 0);
  (id2i_config_feature_ifupdown_ipv4 = 0);
  (id2i_have_stdint_h = 0);
  (id2i_config_feature_show_threads = 0);
  (id2i_config_feature_volumeid_linuxraid = 0);
  (id2i_config_feature_httpd_cgi = 0);
  (id2i_config_feature_less_flags = 0);
  (id2i_config_feature_shadowpasswds = 0);
  (id2i_config_feature_ftp_write = 0);
  (id2i_config_desktop = 0);
  (id2i_test = 0);
  (id2i_config_feature_mount_nfs = 0);
  (id2i_app_init = 0);
  (id2i_openssl_no_ripemd = 0);
  (id2i_engine_conf_debug = 0);
  (id2i_bn_ctx_debug = 0);
  (id2i_config_selinux = 0);
  (id2i_config_feature_adduser_to_group = 0);
  (id2i_config_use_bb_shadow = 0);
  (id2i_openssl_no_md4 = 0);
  (id2i_config_feature_date_nano = 0);
  (id2i_config_feature_grep_fgrep_alias = 0);
  (id2i_config_feature_ip_link = 0);
  (id2i_openssl_no_setvbuf_ionbf = 0);
  (id2i_default_home = 0);
  (id2i_debug_zlib = 0);
  (id2i_config_unxz = 0);
  (id2i_sqlite_omit_analyze = 0);
  (id2i_config_feature_ipcalc_long_options = 0);
  (id2i_b_endian = 0);
  (id2i_config_rpm2cpio = 0);
  (id2i_purify = 0);
  (id2i_config_feature_insmod_version_checking = 0);
  (id2i_config_feature_fdisk_writable = 0);
  (id2i_zlib_shared = 0);
  (id2i_config_ubiattach = 0);
  (id2i_sqlite_omit_blob_literal = 0);
  (id2i_config_feature_wc_large = 0);
  (id2i_simics = 0);
  (id2i_config_feature_netstat_wide = 0);
  (id2i_test_eng_openssl_sha_others = 0);
  (id2i_sqlite_default_memstatus = 0);
  (id2i_modes_debug = 0);
  (id2i_aes_debug = 0);
  (id2i_config_feature_fbset_readmode = 0);
  (id2i___decc = 0);
  (id2i_config_feature_mv_long_options = 0);
  (id2i_config_feature_vi_8bit = 0);
  (id2i_config_feature_runcon_long_options = 0);
  (id2i_config_feature_remote_log = 0);
  (id2i_sqlite_omit_autovacuum = 0);
  (id2i_config_feature_hwclock_long_options = 0);
  (id2i_pkcs12_broken_keygen = 0);
  (id2i_i386 = 0);
  (id2i_config_feature_verbose_cp_message = 0);
  (id2i_config_xz = 0);
  (id2i_config_feature_httpd_setuid = 0);
  (id2i_config_ping6 = 0);
  (id2i_openssl_implements_strncasecmp = 0);
  (id2i_no_windows_braindeath = 0);
  (id2i__win32_wce = 0);
  (id2i_config_feature_tar_oldsun_compatibility = 0);
  (id2i_config_flash_lock = 0);
  (id2i_des_unroll = 0);
  (id2i_config_feature_init_syslog = 0);
  (id2i_config_feature_devpts = 0);
  (id2i_config_feature_non_posix_cp = 0);
  (id2i_sqlite_enable_oversize_cell_check = 0);
  (id2i_debug_sign = 0);
  (id2i_config_feature_vi_colon = 0);
  (id2i_config_feature_run_parts_long_options = 0);
  (id2i_openssl_no_hw_sureware = 0);
  (id2i_config_feature_modutils_symbols = 0);
  (id2i_config_uncompress = 0);
  (id2i_config_feature_gzip_long_options = 0);
  (id2i_config_feature_seamless_xz = 0);
  (id2i_sqlite_omit_pager_pragmas = 0);
  (id2i_debug_pkcs5v2 = 0);
  (id2i_sqlite_omit_deprecated = 0);
  (id2i_sqlite_coverage_test = 0);
  (id2i_config_feature_float_sleep = 0);
  (id2i_config_feature_ls_filetypes = 0);
  (id2i___alpha = 0);
  (id2i_config_nc_extra = 0);
  (id2i_config_feature_prefer_applets = 0);
  (id2i_config_sha256sum = 0);
  (id2i_sqlite_enable_memory_management = 0);
  (id2i_openssl_no_ssl3 = 0);
  (id2i_config_feature_su_checks_shells = 0);
  (id2i_config_feature_compress_bbconfig = 0);
  (id2i_config_feature_init_coredumps = 0);
  (id2i_config_feature_find_maxdepth = 0);
  (id2i_config_feature_wget_statusbar = 0);
  (id2i_config_feature_volumeid_xfs = 0);
  (id2i_sqlite_enable_fts4 = 0);
  (id2i_crypto_mdebug_all = 0);
  (id2i_config_feature_expand_long_options = 0);
  (id2i_openssl_sun_gf2m_div = 0);
  (id2i__file_offset_bits = 0);
  (id2i_config_feature_cpio_p = 0);
  (id2i_config_feature_seamless_z = 0);
  (id2i_config_feature_ifconfig_memstart_ioaddr_irq = 0);
  (id2i_config_feature_brctl_fancy = 0);
  (id2i_config_feature_volumeid_reiserfs = 0);
  (id2i_config_feature_rmdir_long_options = 0);
  (id2i_config_feature_ls_color_is_default = 0);
  (id2i_zlib = 0);
  (id2i_config_feature_fbset_fancy = 0);
  (id2i_data_order_is_big_endian = 0);
  (id2i_config_feature_chat_tty_hifi = 0);
  (id2i_config_chown = 0);
  (id2i_sqlite_omit_or_optimization = 0);
  (id2i_config_sh_math_support_64 = 0);
  (id2i_config_feature_setfiles_check_option = 0);
  (id2i_bf_default_options = 0);
  (id2i_config_feature_find_context = 0);
  (id2i_sqlite_enable_locking_style = 0);
  (id2i_config_feature_mount_helpers = 0);
  (id2i_gost_lib_name = 0);
  (id2i_config_nc_110_compat = 0);
  (id2i_config_feature_xargs_support_confirmation = 0);
  (id2i_aes_wrap_test = 0);
  (id2i_dtls1_ad_missing_handshake_message = 0);
  (id2i_openssl_no_descbcm = 0);
  (id2i_config_feature_tar_from = 0);
  (id2i_config_feature_find_regex = 0);
  (id2i_openssl_no_engine = 0);
  (id2i_openssl_no_rc4 = 0);
  (id2i_openssl_no_buf_freelists = 0);
  (id2i_config_feature_hdparm_hdio_drive_reset = 0);
  (id2i_config_tar = 0);
  (id2i_config_feature_cpio_o = 0);
  (id2i_bn_sqr_comba = 0);
  (id2i_config_feature_call_telinit = 0);
  (id2i_config_feature_volumeid_ntfs = 0);
  (id2i_config_feature_seamless_lzma = 0);
  (id2i_config_feature_wget_timeout = 0);
  (id2i_debug_print_unknown_ciphersuites = 0);
  (id2i_config_feature_udhcpd_write_leases_early = 0);
  (id2i_crypto_mdebug_abort = 0);
  (id2i_openssl_no_idea = 0);
  (id2i_sqlite_omit_foreign_key = 0);
  (id2i_config_feature_insmod_load_map = 0);
  (id2i_config_feature_unexpand_long_options = 0);
  (id2i__m_ix86 = 0);
  (id2i_config_feature_addgroup_long_options = 0);
  (id2i_config_feature_ipv6 = 0);
  (id2i_config_feature_vi_optimize_cursor = 0);
}