#define HAVE_MALLOC_H
#define HAVE_MALLOC_USABLE_SIZE
#define SQLITE_CORE
#define SQLITE_OMIT_BUILTIN_TEST
#define SQLITE_OMIT_LOAD_EXTENSION
#define SQLITE_OS_UNIX 1
#define SQLITE_OS_WINNT
#define SQLITE_SYSTEM_MALLOC
